version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx-fancyindex:latest
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/www/html
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: mysite-app:latest
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
